const mongoose = require('mongoose');
const Product = require('./src/models/product');
const Category = require('./src/models/category');


require('dotenv').config();

const insertSeedData = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI, {}
        ).then(() => {
            console.log("Connected to the database")
        }).catch(e => console.log(e));

        const categories = CATEGORY_GROUPS.reduce((prev, group) => prev.concat(group.categories), []);

       
        await Product.deleteMany()
        await Category.deleteMany()

        await Category.insertMany(
            categories
        );

        for (const product of products) {
            const category = await Category.findOne({ name: product.category });
            product.category = category._id;
        }
        await Product.insertMany(
            products
        );

        console.log(' data inserted successfully');
    } catch (error) {
        console.error('Error inserting  data:', error);

    } finally {
        try {
            await mongoose.connection.close();
            console.log('Connection closed');
        } catch (error) {
            console.error('Error closing connection:', error);
        }
    }
};



CATEGORY_GROUPS = [
    {
        groupName: 'Outerwear',
        categories: [
            { name: 'Rain Jackets', slug: 'rain-jackets' },
            { name: 'Winter Jackets', slug: 'winter-jackets' },
            { name: 'Puffer Jackets', slug: 'puffer-jackets' },
            { name: 'Parkas', slug: 'parkas' },
        ],
    },
    {
        groupName: 'Tops',
        categories: [
            { name: 'Shirts', slug: 'shirts' },
            { name: 'Vests', slug: 'vests' },
            { name: 'Sweaters', slug: 'sweaters' },
            { name: 'Thermal Shirts', slug: 'thermal-shirts' },
        ],
    },
    {
        groupName: 'Bottoms',
        categories: [
            { name: 'Pants', slug: 'pants' },
            { name: 'Leggings', slug: 'leggings' },
            { name: 'Thermal Pants', slug: 'thermal-pants' },
        ],
    },
    {
        groupName: 'Footwear',
        categories: [
            { name: 'Sneakers', slug: 'sneakers' },
            { name: 'Boots', slug: 'boots' },
            { name: 'Slippers', slug: 'slippers' },
        ],
    },
    {
        groupName: 'Accessories',
        categories: [
            { name: 'Gloves', slug: 'gloves' },
            { name: 'Hats', slug: 'hats' },
            { name: 'Umbrellas', slug: 'umbrellas' },
        ],
    },
];

const products = [
    {
        id: 1,
        name: 'Women\'s Two Piece Leggings Set',
        price: 32,
        category: 'Leggings',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_legging_1.jpg',
    },
    {
        id: 2,
        name: 'Women\'s Two Piece Leggings Set',
        price: 32,
        category: 'Leggings',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_legging_2.jpg',
    },
    {
        id: 3,
        name: 'Women\'s Two Piece Leggings Set',
        price: 32,
        category: 'Leggings',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_legging_3.jpg',
    },
    {
        id: 4,
        name: 'Women\'s Two Piece Leggings Set',
        price: 32,
        category: 'Leggings',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_legging_4.jpg',
    },
    {
        id: 5,
        name: 'Women\'s Two Piece Leggings Set',
        price: 32,
        category: 'Leggings',
        size: 'XL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_legging_5.jpg',
    },
    {
        id: 6,
        name: 'Women\'s Lightweight Sweatpants',
        price: 22,
        category: 'Pants',
        size: 'S',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_pant_1.jpg',
    },
    {
        id: 7,
        name: 'Women\'s Stretch Bootcut Pants',
        price: 32,
        category: 'Pants',
        size: 'M',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_pant_2.jpg',
    },
    {
        id: 8,
        name: 'Women\'s Ankle Pants',
        price: 40,
        category: 'Pants',
        size: 'S',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_pant_3.jpg',
    },
    {
        id: 9,
        name: 'Women\'s Cargo Pants',
        price: 27,
        category: 'Pants',
        size: 'M',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_pant_4.jpg',
    },
    {
        id: 10,
        name: 'Women\'s Essential Joggers',
        price: 25,
        category: 'Pants',
        size: 'XS',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_pant_5.jpg',
    },
    {
        id: 11,
        name: 'Women\'s Lined Thermal Bottoms',
        price: 30,
        category: 'Thermal Pants',
        size: 'XS',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_thermalpant_1.jpg',
    },
    {
        id: 12,
        name: 'Women\'s Lined Thermal Bottoms',
        price: 30,
        category: 'Thermal Pants',
        size: 'S',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_thermalpant_2.jpg',
    },
    {
        id: 13,
        name: 'Women\'s Lined Thermal Bottoms',
        price: 30,
        category: 'Thermal Pants',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_thermalpant_3.jpg',
    },
    {
        id: 14,
        name: 'Women\'s Lined Thermal Bottoms',
        price: 30,
        category: 'Thermal Pants',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_thermalpant_4.jpg',
    },
    {
        id: 15,
        name: 'Women\'s Lined Thermal Bottoms',
        price: 30,
        category: 'Thermal Pants',
        size: 'XL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/bottoms/women_thermalpant_5.jpg',
    },
    {
        id: 16,
        name: 'Women\'s Low Heel Fashion Boots',
        price: 48,
        category: 'Boots',
        size: 'Seven',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/footwear/women_boot_1.jpg',
    },
    {
        id: 17,
        name: 'Women\'s Cargo Boots',
        price: 42,
        category: 'Boots',
        size: 'Nine',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_boot_2.jpg',
    },
    {
        id: 18,
        name: 'Women\'s Work Boots',
        price: 32,
        category: 'Boots',
        size: 'Eight',
        color: 'Khaki',
        imageUrl: '/images/rainwear_photos/women/footwear/women_boot_3.jpg',
    },
    {
        id: 19,
        name: 'Women\'s Ankle Boots',
        price: 28,
        category: 'Boots',
        size: 'Five',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/women/footwear/women_boot_4.jpg',
    },
    {
        id: 20,
        name: 'Women\'s Cargo Boots',
        price: 22,
        category: 'Boots',
        size: 'Six',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_boot_5.jpg',
    },
    {
        id: 21,
        name: 'Women\'s Moccasin Slippers',
        price: 21,
        category: 'Slippers',
        size: 'Five',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/footwear/women_slipper_1.jpg',
    },
    {
        id: 22,
        name: 'Women\'s Knit Slippers',
        price: 15,
        category: 'Slippers',
        size: 'Six',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/footwear/women_slipper_2.jpg',
    },
    {
        id: 23,
        name: 'Women\'s Memory Foam Slippers',
        price: 23,
        category: 'Slippers',
        size: 'Seven',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/women/footwear/women_slipper_3.jpg',
    },
    {
        id: 24,
        name: 'Women\'s Fuzzy House Slippers',
        price: 18,
        category: 'Slippers',
        size: 'Eight',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/footwear/women_slipper_4.jpg',
    },
    {
        id: 25,
        name: 'Women\'s Open Toe Slippers',
        price: 21,
        category: 'Slippers',
        size: 'Ten',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_slipper_5.jpg',
    },
    {
        id: 26,
        name: 'Women\'s Slip On Shoes',
        price: 25,
        category: 'Sneakers',
        size: 'Seven',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_sneaker_1.jpg',
    },
    {
        id: 27,
        name: 'Women\'s Canvas Shoes',
        price: 27,
        category: 'Sneakers',
        size: 'Eleven',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_sneaker_2.jpg',
    },
    {
        id: 28,
        name: 'Women\'s Running Sneakers',
        price: 50,
        category: 'Sneakers',
        size: 'Eight',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_sneaker_3.jpg',
    },
    {
        id: 29,
        name: 'Women\'s Running Sneakers',
        price: 52,
        category: 'Sneakers',
        size: 'Ten',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/footwear/women_sneaker_4.jpg',
    },
    {
        id: 30,
        name: 'Women\'s Platform Sneakers',
        price: 35,
        category: 'Sneakers',
        size: 'Nine',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/footwear/women_sneaker_5.jpg',
    },
    {
        id: 31,
        name: 'Women\'s Fleece Lined Parka',
        price: 87,
        category: 'Parkas',
        size: 'L',
        color: 'Mint Green',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_parka_1.jpg',
    },
    {
        id: 32,
        name: 'Women\'s Insulated Parka',
        price: 73,
        category: 'Parkas',
        size: 'XL',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_parka_2.jpg',
    },
    {
        id: 33,
        name: 'Women\'s Faux Fur Lined Parka',
        price: 74,
        category: 'Parkas',
        size: 'S',
        color: 'Olive Green',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_parka_3.jpg',
    },
    {
        id: 34,
        name: 'Women\'s Flannel Parka',
        price: 84,
        category: 'Parkas',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_parka_4.jpg',
    },
    {
        id: 35,
        name: 'Women\'s Fur Hooded Parka',
        price: 129,
        category: 'Parkas',
        size: 'XS',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_parka_5.jpg',
    },
    {
        id: 36,
        name: 'Women\'s Waterproof Puffer Coat',
        price: 129,
        category: 'Puffer Jackets',
        size: 'XS',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_pufferjacket_1.jpg',
    },
    {
        id: 37,
        name: 'Women\'s Windproof Puffer Coat',
        price: 64,
        category: 'Puffer Jackets',
        size: 'M',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_pufferjacket_2.jpg',
    },
    {
        id: 38,
        name: 'Women\'s Waterproof Puffer Coat',
        price: 99,
        category: 'Puffer Jackets',
        size: 'L',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_pufferjacket_3.jpg',
    },
    {
        id: 39,
        name: 'Women\'s Lightweight Puffer Coat',
        price: 72,
        category: 'Puffer Jackets',
        size: 'XL',
        color: 'Blue',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_pufferjacket_4.jpg',
    },
    {
        id: 40,
        name: 'Women\'s Fur Hooded Puffer Coat',
        price: 63,
        category: 'Puffer Jackets',
        size: 'XS',
        color: 'White',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_pufferjacket_5.jpg',
    },
    {
        id: 41,
        name: 'Women\'s Waterproof Rain Jacket',
        price: 49,
        category: 'Rain Jackets',
        size: 'XL',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_rainjacket_1.jpg',
    },
    {
        id: 42,
        name: 'Women\'s Hooded Rain Jacket',
        price: 79,
        category: 'Rain Jackets',
        size: 'L',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_rainjacket_2.jpg',
    },
    {
        id: 43,
        name: 'Women\'s Waterproof Rain Jacket',
        price: 49,
        category: 'Rain Jackets',
        size: 'S',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_rainjacket_3.jpg',
    },
    {
        id: 44,
        name: 'Women\'s Waterproof Rain Jacket',
        price: 79,
        category: 'Rain Jackets',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_rainjacket_4.jpg',
    },
    {
        id: 45,
        name: 'Women\'s Water Resistant Raincoat',
        price: 66,
        category: 'Rain Jackets',
        size: 'M',
        color: 'Yellow',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_rainjacket_5.jpg',
    },
    {
        id: 46,
        name: 'Women\'s Windproof Down Coat',
        price: 64,
        category: 'Winter Jackets',
        size: 'S',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_winterjacket_1.jpg',
    },
    {
        id: 47,
        name: 'Women\'s Ski Jacket',
        price: 59,
        category: 'Winter Jackets',
        size: 'XS',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_winterjacket_2.jpg',
    },
    {
        id: 48,
        name: 'Women\'s Fleece Lined Winter Coat',
        price: 95,
        category: 'Winter Jackets',
        size: 'L',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_winterjacket_3.jpg',
    },
    {
        id: 49,
        name: 'Women\'s Insulated Winter Coat',
        price: 130,
        category: 'Winter Jackets',
        size: 'M',
        color: 'Purple',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_winterjacket_4.jpg',
    },
    {
        id: 50,
        name: 'Women\'s Hooded Winter Coat',
        price: 69,
        category: 'Winter Jackets',
        size: 'XL',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/outerwear/women_winterjacket_5.jpg',
    },
    {
        id: 51,
        name: 'Women\'s Long Sleeve Shirt',
        price: 25,
        category: 'Shirts',
        size: 'L',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/tops/women_shirt_1.jpg',
    },
    {
        id: 52,
        name: 'Women\'s Plaid Shirt',
        price: 35,
        category: 'Shirts',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_shirt_2.jpg',
    },
    {
        id: 53,
        name: 'Women\'s Long Sleeve Shirt',
        price: 14,
        category: 'Shirts',
        size: 'L',
        color: 'Blue',
        imageUrl: '/images/rainwear_photos/women/tops/women_shirt_3.jpg',
    },
    {
        id: 54,
        name: 'Women\'s Long Sleeve Shirt',
        price: 15,
        category: 'Shirts',
        size: 'S',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/tops/women_shirt_4.jpg',
    },
    {
        id: 55,
        name: 'Women\'s Cuffed Shirt',
        price: 27,
        category: 'Shirts',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_shirt_5.jpg',
    },
    {
        id: 56,
        name: 'Women\'s Slouchy Blouse',
        price: 23,
        category: 'Sweaters',
        size: 'XL',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/women/tops/women_sweater_1.jpg',
    },
    {
        id: 57,
        name: 'Women\'s Slouchy Sweater',
        price: 23,
        category: 'Sweaters',
        size: 'XL',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/women/tops/women_sweater_1.jpg',
    },
    {
        id: 58,
        name: 'Women\'s Pullover Sweater',
        price: 30,
        category: 'Sweaters',
        size: 'S',
        color: 'White',
        imageUrl: '/images/rainwear_photos/women/tops/women_sweater_2.jpg',
    },
    {
        id: 59,
        name: 'Women\'s Turtleneck Sweater',
        price: 30,
        category: 'Sweaters',
        size: 'M',
        color: 'Orange',
        imageUrl: '/images/rainwear_photos/women/tops/women_sweater_3.jpg',
    },
    {
        id: 60,
        name: 'Women\'s Chunky Knit Sweater',
        price: 42,
        category: 'Sweaters',
        size: 'M',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/women/tops/women_sweater_4.jpg',
    },
    {
        id: 61,
        name: 'Women\'s Pullover Sweater',
        price: 38,
        category: 'Sweaters',
        size: 'L',
        color: 'White',
        imageUrl: '/images/rainwear_photos/women/tops/women_sweater_5.jpg',
    },
    {
        id: 62,
        name: 'Women\'s Two Piece Thermal Shirt Set',
        price: 26,
        category: 'Thermal Shirts',
        size: 'XS',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_thermalshirt_1.jpg',
    },
    {
        id: 63,
        name: 'Women\'s Two Piece Thermal Shirt Set',
        price: 26,
        category: 'Thermal Shirts',
        size: 'S',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_thermalshirt_2.jpg',
    },
    {
        id: 64,
        name: 'Women\'s Two Piece Thermal Shirt Set',
        price: 26,
        category: 'Thermal Shirts',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_thermalshirt_3.jpg',
    },
    {
        id: 65,
        name: 'Women\'s Two Piece Thermal Shirt Set',
        price: 26,
        category: 'Thermal Shirts',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_thermalshirt_4.jpg',
    },
    {
        id: 66,
        name: 'Women\'s Two Piece Thermal Shirt Set',
        price: 26,
        category: 'Thermal Shirts',
        size: 'XL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/women/tops/women_thermalshirt_5.jpg',
    },
    {
        id: 67,
        name: 'Women\'s Lightweight Zip Vest',
        price: 29,
        category: 'Vests',
        size: 'XL',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/tops/women_vest_1.jpg',
    },
    {
        id: 68,
        name: 'Women\'s Packable Sleeveless Jacket Vest',
        price: 29,
        category: 'Vests',
        size: 'XL',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/women/tops/women_vest_2.jpg',
    },
    {
        id: 69,
        name: 'Women\'s Puffer Vest',
        price: 42,
        category: 'Vests',
        size: 'XS',
        color: 'Orange',
        imageUrl: '/images/rainwear_photos/women/tops/women_vest_3.jpg',
    },
    {
        id: 70,
        name: 'Women\'s Padded Puffer Vest',
        price: 47,
        category: 'Vests',
        size: 'S',
        color: 'Pink',
        imageUrl: '/images/rainwear_photos/women/tops/women_vest_4.jpg',
    },
    {
        id: 71,
        name: 'Women\'s Quilted Zip Vest',
        price: 49,
        category: 'Vests',
        size: 'M',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/women/tops/women_vest_5.jpg',
    },
    {
        id: 72,
        name: 'Men\'s Compression Leggings',
        price: 28,
        category: 'Leggings',
        size: 'M',
        color: 'Navy Blue',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_legging_1.jpg',
    },
    {
        id: 73,
        name: 'Men\'s Compression Leggings',
        price: 28,
        category: 'Leggings',
        size: 'L',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_legging_2.jpg',
    },
    {
        id: 74,
        name: 'Men\'s Compression Leggings',
        price: 28,
        category: 'Leggings',
        size: 'L',
        color: 'White',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_legging_3.jpg',
    },
    {
        id: 75,
        name: 'Men\'s Compression Leggings',
        price: 28,
        category: 'Leggings',
        size: 'XL',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_legging_4.jpg',
    },
    {
        id: 76,
        name: 'Men\'s Compression Leggings',
        price: 28,
        category: 'Leggings',
        size: 'XXL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_legging_5.jpg',
    },
    {
        id: 77,
        name: 'Men\'s Lightweight Jogger Pants',
        price: 32,
        category: 'Pants',
        size: 'L',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_pant_1.jpg',
    },
    {
        id: 78,
        name: 'Men\'s Lightweight Jogger Pants',
        price: 32,
        category: 'Pants',
        size: 'XL',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_pant_2.jpg',
    },
    {
        id: 79,
        name: 'Men\'s Lightweight Jogger Pants',
        price: 32,
        category: 'Pants',
        size: 'XXL',
        color: 'Navy Blue',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_pant_3.jpg',
    },
    {
        id: 80,
        name: 'Men\'s Cargo Pants',
        price: 21,
        category: 'Pants',
        size: 'M',
        color: 'Khaki',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_pant_4.jpg',
    },
    {
        id: 81,
        name: 'Men\'s Everyday Jogger Pants',
        price: 33,
        category: 'Pants',
        size: 'L',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_pant_5.jpg',
    },
    {
        id: 82,
        name: 'Men\'s Two Piece Thermal Underwear Set',
        price: 24,
        category: 'Pants',
        size: 'M',
        color: 'Blue',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_thermalpant_1.jpg',
    },
    {
        id: 83,
        name: 'Men\'s Two Piece Thermal Underwear Set',
        price: 24,
        category: 'Pants',
        size: 'L',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_thermalpant_2.jpg',
    },
        {
        id: 84,
        name: 'Men\'s Two Piece Thermal Underwear Set',
        price: 24,
        category: 'Pants',
        size: 'XL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_thermalpant_3.jpg',
    },
    {
        id: 85,
        name: 'Men\'s Thermal Underwear Pants',
        price: 27,
        category: 'Pants',
        size: 'XL',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_thermalpant_4.jpg',
    },
    {
        id: 86,
        name: 'Men\'s Thermal Underwear Pants',
        price: 27,
        category: 'Pants',
        size: 'XXL',
        color: 'White',
        imageUrl: '/images/rainwear_photos/men/bottoms/men_thermalpant_5.jpg',
    },
    {
        id: 87,
        name: 'Men\'s Hiking Waterproof Boots',
        price: 89,
        category: 'Boots',
        size: 'Twelve',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/men/footwear/men_boot_1.jpg',
    },
    {
        id: 88,
        name: 'Men\'s Hiking Waterproof Boots',
        price: 89,
        category: 'Boots',
        size: 'Thirteen',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/men/footwear/men_boot_2.jpg',
    },
    {
        id: 89,
        name: 'Men\'s Waterproof Work Boots',
        price: 76,
        category: 'Boots',
        size: 'Eight',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/footwear/men_boot_3.jpg',
    },
    {
        id: 90,
        name: 'Men\'s Waterproof Work Boots',
        price: 90,
        category: 'Boots',
        size: 'Ten',
        color: 'Khaki',
        imageUrl: '/images/rainwear_photos/men/footwear/men_boot_4.jpg',
    },
    {
        id: 91,
        name: 'Men\'s Hiking Boots',
        price: 81,
        category: 'Boots',
        size: 'Nine',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/footwear/men_boot_5.jpg',
    },
    {
        id: 92,
        name: 'Men\'s Open Toe Slippers',
        price: 30,
        category: 'Slippers',
        size: 'Seven',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/footwear/men_slipper_1.jpg',
    },
    {
        id: 93,
        name: 'Men\'s Moccasin Slippers',
        price: 28,
        category: 'Slippers',
        size: 'Eight',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/footwear/men_slipper_2.jpg',
    },
    {
        id: 94,
        name: 'Men\'s Moccasin Slippers',
        price: 27,
        category: 'Slippers',
        size: 'Nine',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/men/footwear/men_slipper_3.jpg',
    },
    {
        id: 95,
        name: 'Men\'s Moccasin Slippers',
        price: 25,
        category: 'Slippers',
        size: 'Ten',
        color: 'Khaki',
        imageUrl: '/images/rainwear_photos/men/footwear/men_slipper_4.jpg',
    },
    {
        id: 96,
        name: 'Men\'s Moccasin Slippers',
        price: 33,
        category: 'Slippers',
        size: 'Eleven',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/men/footwear/men_slipper_5.jpg',
    },
    {
        id: 97,
        name: 'Men\'s Running Shoes',
        price: 45,
        category: 'Sneakers',
        size: 'Ten',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/footwear/men_sneaker_1.jpg',
    },
    {
        id: 98,
        name: 'Men\'s Canvas Shoes',
        price: 48,
        category: 'Sneakers',
        size: 'Thirteen',
        color: 'Silver',
        imageUrl: '/images/rainwear_photos/men/footwear/men_sneaker_2.jpg',
    },
    {
        id: 99,
        name: 'Men\'s Running Shoes',
        price: 35,
        category: 'Sneakers',
        size: 'Eleven',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/footwear/men_sneaker_3.jpg',
    },
    {
        id: 100,
        name: 'Men\'s Running Shoes',
        price: 44,
        category: 'Sneakers',
        size: 'Twelve',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/footwear/men_sneaker_4.jpg',
    },
    {
        id: 101,
        name: 'Men\'s Fashion Sneakers',
        price: 65,
        category: 'Sneakers',
        size: 'Eight',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/footwear/men_sneaker_5.jpg',
    },
    {
        id: 102,
        name: 'Men\'s Windproof Parka',
        price: 63,
        category: 'Parkas',
        size: 'XL',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_parka_1.jpg',
    },
    {
        id: 103,
        name: 'Men\'s Winter Parka',
        price: 55,
        category: 'Parkas',
        size: 'M',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_parka_2.jpg',
    },
    {
        id: 104,
        name: 'Men\'s Windproof Parka',
        price: 50,
        category: 'Parkas',
        size: 'S',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_parka_3.jpg',
    },
    {
        id: 105,
        name: 'Men\'s Puffy Hooded Parka',
        price: 53,
        category: 'Parkas',
        size: 'L',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_parka_4.jpg',
    },
    {
        id: 106,
        name: 'Men\'s Winter Parka',
        price: 59,
        category: 'Parkas',
        size: 'M',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_parka_5.jpg',
    },
    {
        id: 107,
        name: 'Men\'s Puffer Jacket',
        price: 56,
        category: 'Puffer Jackets',
        size: 'M',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_pufferjacket_1.jpg',
    },
    {
        id: 108,
        name: 'Men\'s Puffer Jacket',
        price: 42,
        category: 'Puffer Jackets',
        size: 'S',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_pufferjacket_2.jpg',
    },
    {
        id: 109,
        name: 'Men\'s Puffer Jacket',
        price: 59,
        category: 'Puffer Jackets',
        size: 'XL',
        color: 'Blue',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_pufferjacket_3.jpg',
    },
    {
        id: 110,
        name: 'Men\'s Puffer Jacket',
        price: 64,
        category: 'Puffer Jackets',
        size: 'XXL',
        color: 'Orange',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_pufferjacket_4.jpg',
    },
    {
        id: 111,
        name: 'Men\'s Puffer Jacket',
        price: 51,
        category: 'Puffer Jackets',
        size: 'L',
        color: 'Gray',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_pufferjacket_5.jpg',
    },
    {
        id: 112,
        name: 'Men\'s Hooded Rain Jacket',
        price: 61,
        category: 'Rain Jackets',
        size: 'L',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_rainjacket_1.jpg',
    },
    {
        id: 113,
        name: 'Men\'s Waterproof Rain Jacket',
        price: 83,
        category: 'Rain Jackets',
        size: 'XXL',
        color: 'White',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_rainjacket_2.jpg',
    },
    {
        id: 114,
        name: 'Men\'s Water Resistant Rain Jacket',
        price: 79,
        category: 'Rain Jackets',
        size: 'S',
        color: 'Blue',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_rainjacket_3.jpg',
    },
    {
        id: 115,
        name: 'Men\'s Waterproof Rain Jacket',
        price: 77,
        category: 'Rain Jackets',
        size: 'L',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_rainjacket_4.jpg',
    },
    {
        id: 116,
        name: 'Men\'s Lightweight Rain Jacket',
        price: 82,
        category: 'Rain Jackets',
        size: 'M',
        color: 'Yellow',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_rainjacket_5.jpg',
    },
    {
        id: 117,
        name: 'Men\'s Fur Hooded Winter Jacket',
        price: 65,
        category: 'Winter Jackets',
        size: 'M',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_winterjacket_1.jpg',
    },
    {
        id: 118,
        name: 'Men\'s Fur Hooded Winter Jacket',
        price: 65,
        category: 'Winter Jackets',
        size: 'XL',
        color: 'Blue',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_winterjacket_2.jpg',
    },
    {
        id: 119,
        name: 'Men\'s Insulated Winter Jacket',
        price: 65,
        category: 'Winter Jackets',
        size: 'S',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_winterjacket_3.jpg',
    },
    {
        id: 120,
        name: 'Men\'s Winter Snow Coat',
        price: 65,
        category: 'Winter Jackets',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_winterjacket_4.jpg',
    },
    {
        id: 121,
        name: 'Men\'s Skiing Jacket',
        price: 65,
        category: 'Winter Jackets',
        size: 'L',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/men/outerwear/men_winterjacket_5.jpg',
    },
    {
        id: 122,
        name: 'Men\'s Long Sleeve Shirt',
        price: 29,
        category: 'Shirts',
        size: 'S',
        color: 'Beige',
        imageUrl: '/images/rainwear_photos/men/tops/men_shirt_1.jpg',
    },
    {
        id: 123,
        name: 'Men\'s Casual Button Down Shirt',
        price: 26,
        category: 'Shirts',
        size: 'XL',
        color: 'White',
        imageUrl: '/images/rainwear_photos/men/tops/men_shirt_2.jpg',
    },
    {
        id: 124,
        name: 'Men\'s Casual Long Sleeve Shirt',
        price: 23,
        category: 'Shirts',
        size: 'L',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/tops/men_shirt_3.jpg',
    },
    {
        id: 125,
        name: 'Men\'s Long Sleeve Button Down Shirt',
        price: 34,
        category: 'Shirts',
        size: 'XXL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_shirt_4.jpg',
    },
    {
        id: 126,
        name: 'Men\'s Long Sleeve Shirt',
        price: 37,
        category: 'Shirts',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_shirt_5.jpg',
    },
    {
        id: 127,
        name: 'Men\'s Crew Neck Sweater',
        price: 29,
        category: 'Sweaters',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_sweater_1.jpg',
    },
    {
        id: 128,
        name: 'Men\'s V-Neck Sweater',
        price: 37,
        category: 'Sweaters',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_sweater_2.jpg',
    },
    {
        id: 129,
        name: 'Men\'s Hooded Sweater',
        price: 22,
        category: 'Sweaters',
        size: 'XL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_sweater_3.jpg',
    },
    {
        id: 130,
        name: 'Men\'s Hooded Sweater',
        price: 26,
        category: 'Sweaters',
        size: 'L',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/tops/men_sweater_4.jpg',
    },
    {
        id: 131,
        name: 'Men\'s Turtleneck Sweater',
        price: 42,
        category: 'Sweaters',
        size: 'S',
        color: 'Brown',
        imageUrl: '/images/rainwear_photos/men/tops/men_sweater_5.jpg',
    },
    {
        id: 132,
        name: 'Men\'s Thermal Compression Shirts',
        price: 19,
        category: 'Thermal Shirts',
        size: 'S',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_thermalshirt_1.jpg',
    },
    {
        id: 133,
        name: 'Men\'s Thermal Compression Shirts',
        price: 19,
        category: 'Thermal Shirts',
        size: 'M',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_thermalshirt_2.jpg',
    },
    {
        id: 134,
        name: 'Men\'s Thermal Compression Shirts',
        price: 19,
        category: 'Thermal Shirts',
        size: 'L',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_thermalshirt_3.jpg',
    },
    {
        id: 135,
        name: 'Men\'s Thermal Compression Shirts',
        price: 19,
        category: 'Thermal Shirts',
        size: 'XL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_thermalshirt_4.jpg',
    },
        {
        id: 136,
        name: 'Men\'s Thermal Compression Shirts',
        price: 19,
        category: 'Thermal Shirts',
        size: 'XXL',
        color: 'Multi',
        imageUrl: '/images/rainwear_photos/men/tops/men_thermalshirt_5.jpg',
    },
    {
        id: 137,
        name: 'Men\'s Fleece Vest',
        price: 41,
        category: 'Vests',
        size: 'XL',
        color: 'Red',
        imageUrl: '/images/rainwear_photos/men/tops/men_vest_1.jpg',
    },
    {
        id: 138,
        name: 'Men\'s Down Vest',
        price: 35,
        category: 'Vests',
        size: 'S',
        color: 'Tan',
        imageUrl: '/images/rainwear_photos/men/tops/men_vest_2.jpg',
    },
    {
        id: 139,
        name: 'Men\'s Fleece Lined Vest',
        price: 34,
        category: 'Vests',
        size: 'M',
        color: 'Green',
        imageUrl: '/images/rainwear_photos/men/tops/men_vest_3.jpg',
    },
    {
        id: 140,
        name: 'Men\'s Lightweight Winter Vest',
        price: 28,
        category: 'Vests',
        size: 'L',
        color: 'White',
        imageUrl: '/images/rainwear_photos/men/tops/men_vest_4.jpg',
    },
    {
        id: 141,
        name: 'Men\'s Packable Puffer Vest',
        price: 49,
        category: 'Vests',
        size: 'M',
        color: 'Black',
        imageUrl: '/images/rainwear_photos/men/tops/men_vest_5.jpg',
    },
];



insertSeedData();